let EXPORTED_SYMBOLS = [
  "EXTENSION_PREF_BRANCH",
  "PREF_REALM",
  "PREF_DATA_DOMAIN",
  "PREF_DATA_URL",
  "PREF_LOGLEVEL",
  "PREF_DEBUG"
];

const EXTENSION_PREF_BRANCH = "extensions.crownconstruction";
const PREF_DATA_DOMAIN = EXTENSION_PREF_BRANCH +".datadomain";
const PREF_DATA_URL = EXTENSION_PREF_BRANCH +".dataurl";
const PREF_REALM = EXTENSION_PREF_BRANCH +".realm";
const PREF_LOGLEVEL = EXTENSION_PREF_BRANCH +".loglevel";
const PREF_DEBUG = EXTENSION_PREF_BRANCH +".debug";
