let EXPORTED_SYMBOLS = [
  "EXTENSION_PREF_BRANCH",
  "PREF_DATA_DOMAIN",
  "PREF_DBNAME",
  "PREF_SANDBOX_DBNAME"
];

const EXTENSION_PREF_BRANCH = "extensions.crownconstruction";
const PREF_DATA_DOMAIN = EXTENSION_PREF_BRANCH +".datadomain";
const PREF_DBNAME = EXTENSION_PREF_BRANCH +".dbname";
const PREF_SANDBOX_DBNAME = EXTENSION_PREF_BRANCH +".sandboxdbname";

